name: perform pulumi action 
description: pulumi preview and up for moj cross account deployment
inputs:
  stack:
    description: the stack to perform action on
    required: true
  pulumi-action:
    description: the pulumi action to perform
    required: true
  backend-url:
    description: url to login to, including relevant config profile
    required: true
  landing-arn:
    description: full arn of landing role to assume
    required: true
  refresh:
    description: y or n indicates whether the pulumi actions is ran with the refresh flag
    required: true
  pulumi-passphrase:
    description: pulumi passphrase
    required: true
  aws-config-path:
    description: path to the relevant aws config in the repo
    required: false
  work-dir:
    description: 'Location of your Pulumi files. Defaults to ./'
    required: false
    default: ./

runs:
  using: composite
  steps:
    - name: Upgrade AWS CLI & add aws config
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version
        mkdir ~/.aws/
        cp $(if [ ! -s ${{ inputs.aws-config-path }} ];then echo "${{ inputs.aws-config-path }}"; else echo "${{ github.action_path }}/default-aws-config"; fi) ~/.aws/config
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2
      with:
        pulumi-version: ^3.0.0
    - name: login to pulumi backend
      shell: bash
      run: |
        pulumi login '${{ inputs.backend-url }}'
    - name: perform pulumi action
      shell: bash
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ inputs.pulumi-passphrase }}
        INFRA_CREATOR_ROLE_NAME: "DataEngineeringGitHubAction"
      run: |
        cd ${{ inputs.work-dir }}
        pulumi stack select -c ${{ inputs.stack }}
        pulumi config set aws:skipCredentialsValidation true
        pulumi ${{ inputs.pulumi-action }} $(if [ ${{ inputs.refresh }} == y]; then echo "--refresh"; fi) $(if [ ${{ inputs.pulumi-action }} = up ];then echo "--yes"; fi)
        
